description: Diffusion Denoise Smoothing

target:
  # service: amlk8s
  # name: itplabrr1cl1
  # vc: resrchvc

  # service: amlk8s
  # name: ms-shared

  # service: sing
  # name: msrresrchvc

  service: aml
  # name: V100-32G
  # name: V100-32G-sc  
  # name: A100-80G
  name: ussc40rscl

environment:
  # image: amlt-sing/pytorch-1.7.0-cuda11.0-cudnn8-devel
  # image: wuzhiron/pytorch:pytorch1.7-cuda10.1-py37
  image: wuzhiron/pytorch:pytorch1.10.0-cuda11.3-cudnn8-singularity
  setup:
  - pip install scipy
  - pip install pandas
  - pip install statsmodels
  - pip install matplotlib
  - pip install seaborn
  - pip install setGPU
  - pip install attrdict
  - pip install einops
  - pip install -Iv transformers==4.27.4
  - pip install timm

code:
  local_dir: $CONFIG_DIR/

data:
  # local_dir: /D_data/kaqiu/imagenet/
  # remote_dir: imagenet/
  local_dir: /D_data/kaqiu/cifar10/
  remote_dir: cifar/
  # local_dir: /D_data/kaqiu/imagenet32/
  # remote_dir: imagenet32/
  # local_dir: /D_data/kaqiu/ti500k
  # remote_dir: ti500k/
  # local_dir: /D_data/kaqiu/imagenet22k/
  # remote_dir: imagenet22k/  

jobs:
# - name: imgn22k_r152_n025_coslr01_bs1024_w4_e200
#   sku: 2xG8-A100
#   command:
#   - python train.py --config configs/imagenet22k/imgn22k_r152_n025_coslr01_bs1024_w4_e200.json
#   process_count_per_node: 8
- name: diffusion_denoise_smoothing_reproduce_n4
  sku: 4xG8-V100
  command:
  - python train.py --node_num 4
  process_count_per_node: 8